services:
  postgres:
    image: postgres:17.4
    container_name: postgres_yh_labb
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      # 1. Named volume for internal PostgreSQL data (safe & clean)
      - pgdata:/var/lib/postgresql/data

      # 2. Bind mount your CSV import folder into /import inside the container
      - ./yh_data:/import

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres}"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  pgdata:
